\u00ef\u00bb\u00bf#Cau hinh
server.id=1
server.log.display=false
server.port=14444
# db.host=127.0.0.1
db.host=njswdb
db.port=3306
db.user=root
db.password=root_password
db.dbname=nsoz  
db.driver=com.mysql.cj.jdbc.Driver
db.minconnections=10
db.maxconnections=50
mongodb.host=127.0.0.1
mongodb.port=27017
mongodb.dbname=admin
mongodb.user=root
mongodb.password=
websocket.host=ws://localhost
websocket.port=14444
#th\u00c3\u00aam ph\u00e1\u00ba\u00a7n tr\u00c4\u0083m n\u00c3\u00a2ng c\u00e1\u00ba\u00a5p \u00c4\u0091\u00e1\u00bb\u0093
game.upgrade.percent.add=0
#gi\u00e1\u00ba\u00a3m gi\u00c3\u00a1 goosho
game.store.discount=0
#shinwa
game.shinwa.active=false
#ph\u00c3\u00ad b\u00c3\u00a1n
game.shinwa.fee=5000
#t\u00e1\u00bb\u0095ng t\u00e1\u00bb\u0091i \u00c4\u0091a item c\u00c3\u00b3 th\u00e1\u00bb\u0083 \u00c4\u0091\u00e1\u00ba\u00b7t trong shinwa
game.shinwa.max=3
#ng\u00c6\u00b0\u00e1\u00bb\u009di ch\u00c6\u00a1i b\u00c3\u00a1n t\u00e1\u00bb\u0091i \u00c4\u0091a s\u00c3\u00b3 l\u00c6\u00b0\u00e1\u00bb\u00a3ng item cho shinwa
game.shinwa.player.max=30
#l\u00c3\u00b4i \u00c4\u0091\u00c3\u00a0i
game.arena.active=true
#gi\u00e1\u00bb\u009bi h\u00e1\u00ba\u00a1n ip
game.login.limit=7
#s\u00e1\u00bb\u0091 l\u00c6\u00b0\u00e1\u00bb\u00a3ng item hi\u00e1\u00bb\u0087n th\u00e1\u00bb\u008b t\u00e1\u00bb\u0091i \u00c4\u0091a
game.quantity.display.max=65535
server.notification=Hellos
game.data.version=3
game.item.version=3
game.map.version=3
game.skill.version=3
game.maxLv= 131

threadPoolSize=50
scheduledPoolSize=20
game.event=Exe_Z.event.OFF
#Set th\u1eddi gian k\u1ebft th\u00fac event
event.year=2025
event.month=5
event.day=27
event.hour=23
event.minute=59
event.second=59
client.data.size.max=1024

# t\u0103ng dame qu\u00e1i theo % (th\u1ea5p nh\u1ea5t 1)
percent.damemob=2
#True L\u01b0u SQL False L\u01b0u Mongo
open.historySQL=false